pipeline {
    agent any

    environment {
        // Update the PATH variable
        PATH = "C:\\WINDOWS\\SYSTEM32;${env.PATH}"
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/SuchithraChandrasekaran/105Days_ZerodhaClone.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t Pipeline05:latest Day_5'
            }
        }

        stage('Run Script') {
            steps {
                bat 'docker run -v %WORKSPACE%/Day_5:/app Pipeline05:latest'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed!'
        }
    }
}
