pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/SuchithraChandrasekaran/105Days_ZerodhaClone.git'
            }
        }
        stage('Run Python Script') {
            steps {
                // Navigate to the folder and run the Python script
                bat '"C:\\Users\\suchi\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" Day_2\\SimulateBuySell.py'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed!'
        }
    }
}
