pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/SuchithraChandrasekaran/105Days_ZerodhaClone.git'
            }
        }
        
        stage('Build') { 
            steps {
                // Ensure Python is available in the system's PATH
                bat 'python -m py_compile ${env.WORKSPACE}\\Day_2\\SimulateBuySell.py'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed!'
        }
    }
}
